---
title: "Check consistency"
author: "L.A.S."
output: html_document
editor_options: 
  chunk_output_type: console
---

## Setup

```{r setup, eval=T,echo=FALSE }
#load(".RData")
require(igraph)
require(stringr)
require(devtools)
if( require(meweasmo) == FALSE)
  install_github("lsaravia/meweasmo")
if( require(multiweb) == FALSE)
  install_github("lsaravia/multiweb")
require(tidyverse)


```

# Check Weddell Sea

```{r WeddellSea, eval=F,echo=F,message=T,warning=T}
 
#
dtot <- read_csv("Data/WeddellSea_links.csv")

# Check valid names 
#
#
require(taxize)
dfn <- unique(dtot$consumer)
con_names <- gnr_resolve(dfn, best_match_only = TRUE, canonical=TRUE)
# Species not found
anti_join(data.frame(user_supplied_name=dfn),con_names)
# 1 Cadulus dalli antarcticum

dfn <- unique(dtot$resource)
res_names <- gnr_resolve(dfn, best_match_only = TRUE, canonical=TRUE)
anti_join(data.frame(user_supplied_name=dfn),res_names)
# 1             Phytodetritus
# 2                  Sediment
# 3         Silicioflagellata
# 4 Cadulus dalli antarcticum

gM <- graph_from_edgelist(as.matrix(dtot), directed  = T)

# Basal species
#
basal_sp <- (V(gM)[ (degree(gM,mode="in")==0) ])$name
basal_sp

# CLasificación completa
# clasall <- classification(basal_sp, db = 'itis') # 24 not found

# Solamente clase
class <- tax_name(basal_sp, get = "class", db = "itis")
class %>% count(is.na(class))                                # 27 NA
class <- class%>% mutate(genera= stringr::word(query)) %>% rename( species = query ) %>% select(genera,species,class)

unique(class$genera)

#write_tsv(class,"Data/WeddellSea_basal.dat")
class<-read_tsv("Data/WeddellSea_basal.dat")

# Genera tabla genero clase para reemplazar el nombre de la especie por la clase solo en el caso de Bacillariophyceae

#remove "Phytodetritus" and "Sediment"
row_names_to_remove<-c("Phytodetritus","Sediment")
class<-class[!(class$genera %in% row_names_to_remove),]

class  <- class %>% 
mutate(class = case_when(class %in% c("Prymnesiophyceae", "Chrysophyceae") ~ "Phytoplankton_other",TRUE ~ class))

class  <- class %>% 
mutate(class = case_when(species %in% c("Silicioflagellata") ~ "Phytoplankton_other",TRUE ~ class))

#add a resource link to Alcyonium antarcticum
dtot<-rbind(dtot, c("Phytodetritus", "Alcyonium antarcticum"))

#
gencla <- class %>% filter(!is.na(class)) %>%  distinct(genera,class) %>%  filter(class=="Bacillariophyceae")
#
gencla <- add_case(gencla, genera="Nitzschia", class="Bacillariophyceae" )
dim(gencla)

gencla_other <- class %>% filter(!is.na(class)) %>%  distinct(genera,class) %>%  filter(class=="Phytoplankton_other")

sapply( 1:nrow(dtot), function(i) {
  res_gen <- stringr::word(dtot$resource[i]) 
  rep_cla <- gencla %>% filter(genera == res_gen) 
  if(nrow(rep_cla)==1)
    dtot$resource[i] <<- rep_cla$class
  
  rep_cla_other <- gencla_other %>% filter(genera == res_gen) 
  if(nrow(rep_cla_other)==1)
    dtot$resource[i] <<- rep_cla_other$class
})

#
collapsed_w <- dtot %>% distinct()
gM <- graph_from_edgelist(as.matrix(collapsed_w), directed  = T)

# Basal species
#
new_basal_sp <- (V(gM)[ (degree(gM,mode="in")==0) ])$name
new_basal_sp

#I FIXED THESE ISSUES!!! (Susanne)

#        Dictyocha     Chrysophyceae --> phytoplankton == silicioflagellata 
#      Phaeocystis  Prymnesiophyceae --> phytoplankton
#      
#   Alcyonium antarcticum  --> Coral not basal
#   Silicioflagellata     --> ??? Chrysophyceae? 
# 

calc_topological_indices(gM)
write_csv(collapsed_w,"Data/Weddell_collapsed_links_2.csv")
```
