---
output:
  pdf_document:
    latex_engine: xelatex
    keep_tex: yes
bibliography: JAE_Review.bib
csl: "environmental-reviews.csl"
documentclass: article
geometry:
- vmargin=1in
- hmargin=1in
header-includes:
- \usepackage{pdflscape,booktabs}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
- \usepackage[running]{lineno}
- \linenumbers
---

# The response of trophic interaction networks to multiple stressors along a large-scale latitudinal range in the Southern Hemisphere
## Running Title: Marine stressors in the Southern Hemisphere

Tomás I. Marina^1^, Leonardo A. Saravia^1,2,\*^, Iara D. Rodriguez^3^,
Manuela Funes^4^, Georgina Cordone^5^, Santiago R. Doyle^3,6^, Anahí
Silvestro^6^, David E. Galván^5^, Susanne Kortsch^7^ & Fernando
Momo^3,6^

^1^ Centro Austral de Investigaciones Científicas (CADIC-CONICET),
Ushuaia, Argentina;

^2^ Instituto de Ciencias Polares, Ambiente y Recursos Naturales,
Universidad Nacional de Tierra del Fuego (UNTdF), Ushuaia, Argentina;

^3^ Instituto de Ciencias, Universidad Nacional de General Sarmiento
(UNGS), Los Polvorines, Argentina;

^4^ Instituto de Investigaciones Marinas y Costeras (IIMyC-CONICET), Mar
del Plata, Argentina;

^5^ Centro Para el Estudio de Sistemas Marinos (CESIMAR-CONICET), Puerto
Madryn, Argentina;

^6^ Instituto de Ecología y Desarrollo Sustentable
(INEDES-CONICET-UNLu), Luján, Argentina;

^7^ Tvärminne Zoological Station, University of Helsinki, Hanko,
Finland.

\* corresponding author: Leonardo A. Saravia. Centro Austral de
Investigaciones Científicas (CADIC-CONICET), Ushuaia, Argentina.
lasaravia@untdf.edu.ar

## Abstract

Ecological networks offer valuable insights into community structure, key species identification, and ecosystem management. Understanding how these networks respond to global change stressors is of increasing interest, especially along geographical gradients.
This review summarizes potential stressor responses in marine food webs from the Southwest Atlantic to the Antarctic (45 - 78°S), encompassing areas such as San Jorge Gulf, Beagle Channel, Burdwood Bank, Scotia Sea, Potter Cove, and the Weddell Sea in Antarctica. The objectives are: 1) to describe the structure of marine food webs along this latitudinal axis using a network approach; 2) to identify predominant global change-related stressors affecting each ecosystem; and 3) to summarize observed food web changes and hypothesize on stressor impacts. The effects of stressors were primarily reviewed at the species level.
Alternative hypotheses for each study area were formulated considering: a) main stressors; b) impacted parameters; c) node-level species properties; and d) network-level food web properties. Global warming emerges as the most common stressor among the studied areas across the latitudinal gradient, except in the Beagle Channel and Burdwood Bank, where alien species introduction and fisheries are more influential. We offer a series of alternative hypotheses on how warming may affect the food webs. This review emphasizes the benefits of using a network approach to understand and predict stressor effects in Southern Hemisphere marine ecosystems. This approach provides a holistic understanding of ecosystems, which enhances our ability to identify key species and their interactions, offering insights for ecosystem management and conservation in the face of global change stressors.

Keywords: stressors, global warming, food webs, latitudinal gradient, Southern Hemisphere

## 1. Introduction

The application of a network perspective has emerged as a powerful tool to tackle the complexity of species interactions, facilitating a better understanding of the structure and functioning of ecosystems [@Belgrano2005; @Thompson2012]. Trophic networks (or food webs) allow identifying properties and key species that may be crucial for ecosystem stability, and hence important for ecosystem management and biodiversity conservation [@Thompson2012].
There is a growing interest in understanding how ecological networks respond to environmental and anthropogenic stressors along geographical gradients [@Bauer2022; @Cirtwill2015]. Yet, only a few studies have described variation in food web structure along latitudinal gradients in marine ecosystems. The few that have come from the Global North [@Wood2015; @Kortsch2019; @Pecuchet2020], whereas no studies, nor meta-analyses, on geographical variation in marine food webs exist for the Global South (Southern Hemisphere).

Here we review for the first time stressor responses of marine food webs for areas located along a Southwest Atlantic to Antarctic gradient (45 - 78°S, Figure 1). We considered proven and expected changes in food webs driven by global change-related stressors in selected areas along this large-scale latitudinal range.
The aim of this review is threefold: 1) describe the complexity and structure of marine food webs along the Southwest Atlantic to Antarctic axis from a network perspective; 2) identify the ongoing global change-related stressors for each marine ecosystem containing the food webs; and 3) review proven food web changes and elaborate on a series of alternative hypotheses on how the identified stressors might affect food web features (energy flow, stability and topology), combining information on node- and network-level properties. 
To identify the main stressors, we performed an exploratory and configurative review [@Haddaway2015], where we considered more than 200 peer-reviewed articles retrieved mainly from Google Scholar using keywords combining location ( "San Jorge Gulf", "Beagle Channel", "Burdwood Bank", "Scotia Sea", "Weddell Sea", "Potter Cove") and stressors ("acidification", "alien species", "climate change", "contamination", "fishery", "glacier retreat", "global warming", "ice scouring", "invasive species", "marine contaminant", "microplastics", "mercury", "pollution", "sea ice", "sea warming", "urban waste"). Additionally, we specifically searched for publications by authors we know may have conducted related studies in the area including grey literature. We performed this type of review because our objective was to formulate evidenced-based hypotheses rather than providing an exhaustive list of species-level stressors for each ecosystem.
Finally, we suggest which additional data and analyses are needed to gain insights into the stressors’ effects on food web properties in the Southwest Atlantic to Antarctic region.

## 2. Assessment of the food web structure and stressors in the Southwest Atlantic - Antarctic region

The Southwest and the Atlantic sectors of the Southern Ocean comprise one of the most biologically productive regions of the world's oceans [@Acha2004; @Latorre2023]. The referred region extends from San Jorge Gulf (45°S) in the Patagonian shelf to the Weddell Sea (78°S) in the Southern Ocean and covers a well-connected oceanic area [@Matano2010; @Guihou2020].

Throughout this region, many studies address the ecology of predator-prey relationships but most of these studies are restricted to a few interacting species or certain components of the food web such as fish, crustaceans, and benthos (e.g., @Vinuesa2007, @Padovani2012, @Pasotti2015, @Riccialdelli2020, @Saunders2019, @Pasti2021, @Cordone2022). Only few studies consider the complexity of trophic interactions within highly resolved food webs containing hundreds of species, ranging from phytoplankton, zooplankton, benthos, fish, seabirds to whales (but see @Jacob2011, @Marina2018, @Funes2022, @Lopez-Lopez2022, @Rodriguez2022, @Marina2024a). Neglecting this complexity might lead to a misunderstanding of the structure and functioning of the ecosystems and ultimately reduce the ability to predict ecosystem responses to perturbations [@Montoya2009].

The Southwest Atlantic - Antarctic marine biota has been and is currently subjected to a variety of stressors (e.g., sea warming, glacial retreat, ice changes, acidification, species invasion, fisheries, and contamination). Here, we consider a stressor as a global change variable if it causes a quantifiable change, irrespective of its direction (increase or decrease), in a biological response [@Orr2020]. This aligns with the framework established during the early years of the International Geosphere-Biosphere Programme (IGBP) for classifying driving forces. These driving forces are grouped into those that modify the composition of the Earth's fluid envelopes (e.g., sea warming, acidification), and those that originate as local processes but attain global importance due to their widespread impact (e.g., species invasion, fisheries) [@Vitousek1992; @Sage2020].
Although it is well-known that multiple stressors act in concert at any given time (e.g., warming and fishery; acidification and contaminants) [@Gutt2021], to date stressor assessments have been performed individually. Moreover, the potential for interactive effects of two or more stressors (synergy or antagonism) [@Cote2016] is almost unknown for the region [@Rowlands2021].

In this review, we included six large marine areas in the Southern Hemisphere for which highly-resolved empirical food webs in terms of species diversity and trophic interactions have been previously described: (1) San Jorge Gulf (~45 - 47°S, 65 - 68°W) [@Funes2022], (2) Beagle Channel (~54°S, 68°W) [@Rodriguez2022], (3) Burdwood Bank (~54°S, 59°W) [@Marina2024a], (4) Scotia Sea (~48 - 58°S, 50°W) [@Lopez-Lopez2022], (5) Potter Cove (62°S, 58°W, Antarctica) [@Marina2018], and (6) Weddell Sea (74 - 78°S, 30°W, Antarctica) [@Jacob2011; @Marina2024] (Figure 1). The geographic locations of these marine biomes span from temperate Atlantic waters to Antarctic, and are exposed to global change stressors (e.g., sea warming, glacial retreat, fishery, pollution) [@Sage2020], of which some are locally more important, e.g., fisheries in the San Jorge Gulf or glacial retreat in the Antarctic.

In the following subsections, we describe the complexity and structure of the mentioned marine food webs, identify the main stressors, the species (or trophic species), and the parameters affected. Table 1 summarizes the properties of the marine food webs (number of nodes, trophic interactions, connectance, path length, mean trophic level, and omnivory); Table 2 provides a list of the main stressors affecting species inhabiting each area, considering: stressors’ nature, species and parameter affected, and locality.

![ Map of the study areas along the southwest Atlantic - Antarctic latitudinal gradient. The areas are marked with numbers from one to six. Smaller areas (1. San Jorge Gulf, 2. Beagle Channel, 3. Burdwood Bank, and 5. Potter Cove) are shown on the panels to the left, whereas the larger areas (4. North and South Scotia Sea, and 6. Weddell Sea) are marked with a red rectangle on the map. The map was drawn using the ‘marmap’ R package [@Pante2023]. Continental contour shapefiles were obtained from www.ign.gob.ar.](Figures/Map_final.jpg){width="6.27in"
height="3.528in"}

### 2.1 San Jorge Gulf

San Jorge Gulf is the northernmost study area considered in this review (Figure 1), located from Cabo dos Bahias (44°55'S) to Cabo tres Puntas (47°06'S). It is a partially enclosed basin spanning approximately 34,000 $\text{km}^2$ and ~100 m of maximum depths. The gulf’s productivity supports large invertebrate and vertebrate fisheries [@Gongora2012], as well as marine mammal and seabird populations [@Yorio2009]. Two prominent frontal systems meet in the shallower northern and southern ends of the gulf (with depths ~40 m), which are also the places of highest productivity [@Glembocki2015].

The San Jorge Gulf food web contains 165 nodes (trophospecies) and 1015 trophic interactions with a connectance of 0.04. The percentage of top predators is 16%, 78% of the nodes are intermediate and 6% are basal; 60% of the consumers are omnivorous (Table 1). The most connected nodes are the Argentine red shrimp *Pleoticus muelleri*, the squat lobster *Gimothea gregaria*, squids (*Illex argentinus* as dominant species), and Amphipoda. Notably, these nodes are positioned at mid-trophic levels in the food web (3, 2.5, 3.6, and 2, respectively) [@Funes2022].

The gulf is subject to several global change stressors (Table 2), especially fisheries [@Gonzalez-Zevallos2006; @Gonzalez-Zevallos2011; @Galvan2022]. By discarding species, trawl fisheries add new trophic interactions to the food web which results in decreasing trait variability and stability of the system [@Funes2022; @Rincon-Diaz2021]. Moreover, this has changed the availability of resources to some predators. For example, the Argentine hake *Merluccius hubbsi*, one of the main bycatch species, has become a prey item of non-diving seabirds, like the kelp gull *Larus dominicanus* [@Gonzalez-Zevallos2006] and reef fish [@Funes2019]. Although juveniles of *M. hubbsi* is largely the main bycatch species, 29 cartilaginous and 69 bony local fish species were also registered as incidental catch between 2005 and 2014 [@Bovcon2013; @RuibalNunez2020]. This level of impact has triggered a shift in the functional diversity of fish assemblages in the gulf, homogenizing their trophic function [@Rincon-Diaz2021], for example in the sites with the historical highest fishing activity, the fish assemblage experienced a relative increase in midwater fusiform species and lost variability in their depth range [@Rincon-Diaz2021]. Other functional changes were a decrease in the maximum sizes of individual fish, together with a drop in elasmobranch biomass and an increase in crustacean biomass [@Funes2020]. The significant increase in crustacean biomass was mainly due to the increase in the Argentine red shrimp and the squat lobster [@Funes2020]. These species have become the most important prey for the most abundant fish in the area, the Argentine hake and the narrownose smooth-hound *Mustelus schmitti* [@Belleggia2017; @Pasti2021]. However, since commercial fisheries ceased their activities in the San Jorge Gulf in 2015 (Annex I, Resolution CFP No 7/2018), the effects mentioned above from trawl fisheries on the structure and function of the ecosystem may have changed since then. Nowadays only small-scale trawling from artisanal fishery is practiced in the gulf.
Sea warming is another important stressor in the San Jorge Gulf, because of the southward shifts of northern fish populations to the area [@Galvan2022]. Signs of sea warming have been detected in the gulf and nearby regions. Anomalous bottom temperature increments of up to 2°C have been observed in the gulf since 2000 [@Isla2024], and a positive trend in sea surface temperature of 0.3°C/0.4°C per decade over a 30-year series [@Saraceno2022; @Risaro2022]. Additionally, a positive trend in sea surface temperature (~0.5 °C increase in the last 20 years) has been reported for the Nuevo and San Jose Gulfs, both located close to and northward of the San Jorge Gulf [@Williams2023]. The region is especially prone to be affected by climate-driven shifts in species ranges because it is situated in the ecotone of two biogeographic provinces, the Argentine (30°S - 44°S) and the Magellanic (43°S - 55°S) [@Balech2008]. In addition to tropicalization from northern fish populations, alien species are also documented to affect demersal assemblages of fish and macroinvertebrates in the gulf [@Galvan2022].
Finally, the gulf is exposed to urban and industrial pollution [@Verga2020]. In particular, there is an oil monobuoy from which oil manipulation and general oil transport along the Patagonian coast registered several oil spills and chronic oil discharges [@Garcia-Borboroglu2008]. Other marine systems impacted by the oil spill have shown extraordinary mortality events for cetacean [@Litz2014], sea turtles [@Wallace2017], and important decrease in marine bird populations [@Irons2000] sea otters [@Garrott1993] and macroalgae [@Southward1978], with cascading effects throughout the food web [@Peterson2001].

### 2.2 Beagle Channel

Located at a more southern latitude (~54°S, 68°W), the Beagle Channel (Figure 1) is an interoceanic passage at the southernmost tip of South America, spanning 240 km in length and 5 km in width (~1200 $\text{km}^2$), with a depth range of 0 - 140 m. It features complex coastlines, varying bathymetry, a prevailing west-to-east circulation pattern, and a significant longitudinal gradient of glacial freshwater discharge [@Schloss2023]. @Bruno2023 suggests that locally produced suspended particulate organic matter (mostly composed of phytoplankton) and organic matter accumulated in the sediments (macroalgae-originated detritus) are the primary food sources for the marine ecosystem, as opposed to allochthonous materials.

The Beagle Channel food web includes 145 nodes and 1115 trophic interactions with a connectance of 0.05 (Table 1). This food web is hypothesized to have a wasp-waist structure (i.e., the structure and dynamics of the ecosystem are regulated primarily by mid-trophic level species), where the following species play a crucial role in the dynamics of the ecosystem: Fueguian sprat *Sprattus fuegensis*, longtail southern cod *Patagonotothen ramsayi*, black southern cod *P. tessellata*, frogmouth *Cottoperca trigloides*, and squat lobster *G. gregaria* [@Riccialdelli2020]. Moreover, the squat lobster has been identified as a species linking food web modules and connecting the entire food web [@Rodriguez2022].

One of the main local stressors in the Beagle Channel is the introduction of invasive species (Table 2). Salmonidae were introduced to Tierra del Fuego in the 1930s. Especially, the Chinook salmon *Oncorhynchus tshawytscha* causes concern. The detection of this species in Tierra del Fuego dates back to April 2006, and its population has been expanding since then [@Nardi2019]. Being a top predator, the Chinook salmon can compete for resources with several native predators in the Beagle Channel [@Correa2008], but also prey on them. This is the case for Notothenioids (*Eleginops maclovinus*, *Patagonotothen tessellata*, *P. cornucola*, *P. sima*, *Paranotothenia magellanica*, *Harpagifer bispinis*), the Atherinidae *Odontesthes smitti* and *O. nigricans*, the Fuegian sprat, and larvae of king crabs (*Lithodes antarcticus* and *Paralomis granulosa*) [@Fernandez2010]. @Ciancio2008 observed that Chinook salmon primarily feeds on sprats in the Southern Patagonian Shelf Ecosystem area and display trophic levels comparable to those of intermediate-sized fish and cephalopod predator species, showing significant dietary overlap with the Magellanic penguin *Spheniscus magellanicus*. Another potential competitor for Chinook salmon in the Beagle Channel, sharing a similar diet, is the native Commerson's dolphin *Cephalorhynchus commersonii* [@Riccialdelli2013]. In invaded ecosystems, predation emerges as the primary driver of significant damage, often leading to cascading effects impacting even primary producers [@David2017].
In the Beagle Channel, other stressors include contaminants like metals, perfluorinated compounds, hydrocarbons, and microplastics found in animal tissue (algae, mussel, fish, and guano) and sediments [@Duarte2011; @Llorca2012]. Carbon and carbohydrate levels in Ushuaia Bay's (54°48′S, 68°18′W) surface sediments are similar to hypertrophic ecosystems (i.e., greater input of nutrients than an eutrophic situation), along with hydrocarbons and heavy metals linked to port and industrial activities [@Gil2011; @Commendatore2012]. @Ferreira2021 showed that the black southern cod in Ushuaia Bay may be exposed to endocrine-disrupting compounds from urban and industrial pollution.
Moreover, @Perez2020 and @Ojeda2021 found microplastics in the Chilean mussel *Mytilus chilensis* and the sea snail *Nacella magellanica*, respectively. These studies link pollutants to port and industrial activities of Ushuaia; we therefore expect the area of the Beagle Channel closest to the city to be the most affected by contaminants. 
Contaminants potentially spread through the food web, from lower to higher trophic level taxa. In the Beagle Channel and Atlantic coast of Tierra del Fuego food webs mercury concentrations rose with benthivory, and higher mercury was found in phytoplankton and the squat lobster. This latter species connects pelagic and benthic habitats, so any disruption to them could disrupt the food web [@Rodriguez2022]. @Dodino2022 found the highest mercury levels in Magellanic penguin feathers from offshore colonies in Tierra del Fuego. Recently, Ushuaia's kelp forests have also seen changes in composition along with a decrease in biodiversity as a result of urban pollution [@Kaminsky2024]. It is important to note that sea warming might be a less significant stressor in the Beagle Channel compared to the other areas, as global warming is melting glaciers and the influx of cold freshwater is actually slightly cooling the seawater [@Saraceno2022].

### 2.3 Burdwood Bank

The so-called Burdwood Bank ecosystem comprises Marine Protected Areas Namuncurá - Burdwood Bank I and II (~54°S, 59°W), meaning the shallow submarine plateau named Burdwood Bank with a 200 m isobath boundary, and a deep slope that reaches 4000 m in depth, respectively [@APN2022] (Figure 1). Physical features in the plateau are fairly stable, with salinity averaging 34 all year round and temperature ranging between 4 and 8°C [@Acha2004]. The plateau is surrounded by steep flanks of up to 4000 m depth, protected by the Marine Protected Area Namuncurá - Burdwood Bank II (32,000 $\text{km}^2$). Intense upwelling and mixing occur in relation to the slope, entraining deep nutrient-rich waters into the photic layer [@Matano2019], and resulting in a fairly homogeneous water column both spatially and temporally [@Matano2019].

The Burdwood Bank food web comprises 379 nodes and 1788 interactions, with a connectance of 0.01, and an asymmetric degree distribution (i.e. most of the species have a relatively low number of interactions and few species concentrate most of them). Almost half of the consumers are omnivores (48%), and the network displays a small-world pattern [@Marina2024a] (Table 1). This network pattern implies a rapid spread of a perturbation (e.g., contaminant, population fluctuation, local extinction) throughout the food web due to a short distance among species but, at the same time, a greater resistance caused by the confinement of perturbations mainly within subnetworks as a result of a high clustering coefficient [@Bornatowski2017; @Dormann2017].

The main stressors reported for the ecosystem of the Marine Protected Areas Namuncurá within Burdwood Bank I and II are related to human activities such as fisheries and contamination (Table 2). Several fisheries targeting demersal fish operate in the vicinity and within the Marine Protected Areas. The fishery of the Patagonian toothfish *Dissostichus eleginoides* has gained prominence in recent years [@Allega2020; @Gorini2021]. Although these are regulated by the Argentinean government, incidental bycatches do occur, where demersal fish of the genera *Coelorinchus* and *Macrourus*, seabirds and benthic invertebrates (30+ taxa) are the most common bycatches [@Gaitan2016; @Martinez2022]. Noteworthy, among the invertebrates caught, eight species are indicator taxa of vulnerable marine ecosystems [@Gaitan2016; @Schejter2021]. However, independent assessments of these bycatches suggest no significant impact on the populations [@Gaitan2016; @Martinez2022]. Besides bycatches, seabirds are being affected by fisheries due to discards, altering their diet; the most frequently encountered species are black-browed albatross *Thalassarche melanophris*, Southern giant petrel *Macronectes giganteus*, Cape petrel *Daption capense*, Southern royal albatross *Diomedea epomophora*, Northern giant petrel *M. halli*, and white-chinned petrel *Procellaria aequinoctialis* [@Tamini2023]. Nevertheless, there is a lack of knowledge considering their role in the ecosystem and the potential joint effect of both target fish and bycatch in a broader food web framework.
Contaminants such as microplastics and mercury occur in the water column of the Burdwood Bank ecosystem [@Cossi2021; @DiMauro2022; @Fioramonti2022]. Microplastics are distributed along the entire water column, from surface to deep waters (3-2450 m) [@DiMauro2022]. More importantly, microplastics were found in soft tissues of benthic macroinvertebrates (sea stars *Henricia obesa* and *Odontaster penicillatus*) and benthopelagic fish (*Patagonotothen guntheri* and *P. ramsayi*), which not only incorporated the contaminant from the environment through their filter-feeding system but could also get it indirectly from prey organisms already containing plastics in their tissues [@Cossi2021]. Notably, one of the contaminated species is the longtail southern cod *P. ramsayi*. This species is part of the core group of species that drive the ecosystem through the suggested wasp-waist control [@Riccialdelli2020].
Mercury transfer and biomagnification are occurring at a greater pace than near coastal areas such as the Beagle Channel [@Fioramonti2022]. The Fuegian sprat *S. fuegensis*, a pelagic fish with a mid-trophic level in the food web, has the highest levels of mercury recorded [@Fioramonti2022]. Considering the wasp-waist control of the Fuegian sprat in the food web [@Riccialdelli2020], a rapid and widespread contamination to the top predators is expected [@Fioramonti2022].
Despite evidence of warming of surface, mid-water and bottom layers (100 m) in Burdwood Bank [@Franco2020], studies on the oceanographic aspects of the system are lacking. Warming impacts on the species and trophic interactions in Burdwood Bank are also unknown.

### 2.4 Scotia Sea

The Scotia Sea is a deep-sea basin (~48 - 58°S, 50°W), delimited by the Drake Passage to the West and by the island complex of the Scotia Arc to the North, East, and South, with an approximate extension of 1.5 x 106 $\text{km}^2$ and a depth range of 0 - 3000 m [@Murphy2006] (Figure 1). Its oceanography is dominated by the Antarctic Circumpolar Current, which is spatially structured by frontal systems [@Whitworth1980]. The South Antarctic Circumpolar Current Front subdivides the Scotia Sea into two biogeographic regions: the Northern Scotia Sea, characterized by higher and more variable temperatures, and the Southern Scotia Sea, characterized by lower and more stable temperatures and influenced by seasonal sea ice [@Raymond2011].

Analysis of the Northern and Southern Scotia Sea food webs shows that the former is relatively more complex in terms of number of species and links than the latter: with more species richness (218 vs 192) and interactions (10008 vs 7241) and a slightly higher connectance (0.21 vs 0.20). Mean path length is shorter in the Northern Scotia Sea food web, whereas the Southern Scotia Sea network displays a greater proportion of omnivores and a lower mean trophic level [@Lopez-Lopez2022] (Table 1).

The Scotia Sea is a vast and heterogenous oceanic region, where especially the zone around South Georgia island represent an area of interest, here referred to as ‘Northern Scotia Sea’. The majority of studies analyzing the stressors’ effects come from this area (e.g., @Murphy2007; @Whitehouse2008; @Trathan2023) (Table 2).
The main stressor of the Scotia Sea is commercial fisheries. Krill fishery on *Euphausia superba* not only impacts the targeted species, but also the many predators that depend on it as a food source [@Hilborn2017]. Yet, data currently available from monitoring of krill and its predators remain insufficient, hence identifying the potential fishery impacts on the ecosystem is difficult [@Trathan2021]. Apart from krill fishery, two other commercial fisheries operate in the Scotia Sea, targeting Patagonian toothfish species *D. eleginoides* and *Dissostichus mawsoni*. The *D. eleginoides* stock is linked to the stock at South Georgia (‘Northern Scotia Sea’) [@Collins2010], while the *D. mawsoni* stock is linked to the Antarctic continental shelf (‘Southern Scotia Sea’) [@Soeffker2022]. Recently, @Trathan2023 has identified several concerns regarding aspects of these fisheries, highlighting that it is crucial to recognize ongoing changes such as the recovery of baleen whales and climate change. These factors increase the uncertainty for fishery managers, necessitating direct consideration in the management of harvested and dependent species.

The Scotia Sea has experienced one of the largest levels of warming within the polar regions [@Whitehouse2008]. Together with the Southern Annular Mode anomalies, this has caused a long-term decrease in krill abundance; more pronounced in the northern than in the southern Scotia Sea [@Murphy2007]. Over the past 90 years, the Antarctic krill *E. superba* also showed an increase in mean body length [@Atkinson2019], likely altering predator-prey interactions. Moreover, it allows krill to reach colder feeding grounds near the seabed, with the potential to link krill to unexpected predators such as demersal fish [@Schmidt2011]. Because of warming, the krill distribution has shifted southward [@Atkinson2019], changing the food web from a krill-based to a non-krill-based, where myctophid fish and squid are playing important roles as key species in a wasp-waist controlled system [@Saunders2019]. While the krill distribution has shifted southward, the most abundant calanoid copepods have maintained their distribution [@Tarling2018].
Mercury transfer and biomagnification are current processes occurring in the Scotia Sea, where the total concentration of contaminants increase with trophic level and are highest in notothenioid and myctophid fish (e.g. *D. eleginoides*, *Gymnoscopelus nicholsi*), and seabirds [@Seco2021]. During years of low Antarctic krill abundance, predators must deal with both the stress of reduced prey availability and the concurrent rise in mercury exposure [@Seco2021].

### 2.5 Potter Cove (Antarctica)

In the Antarctic realm, Potter Cove is a ~9 $\text{km}^2$ fjord with a depth range of 0 - 200 m located at 25 de Mayo/King George Island (62°S, 58°W) on the South Shetland Islands of the West Antarctic Peninsula (Figure 1). The cove, bordered by the Fourcade Glacier, is divided into three areas: a) the internal cove, a high glacier-influenced, soft sediment zone with a 50 m maximum depth; b) the central cove, a mixed substrate area with low meltwater influence and an 80 m maximum depth; and c) the external cove, ice-free for 60 years with a 185 m maximum depth and rocky substrate [@Jerosch2018]. Potter Cove's high-latitude location results in variable environmental conditions due to photoperiod length seasonality. Sea ice often covers this area in winter [@Schloss2012]. With low phytoplankton biomass, macroalgae, and microphytobenthos are likely the primary food sources for secondary benthic production [@Quartino2008].

The Potter Cove food web includes 110 nodes and 649 interactions, and a connectance of 0.05 (Table 1). It presents an asymmetric degree distribution and a modular structure, i.e., groups of species interact more strongly with each other within modules than with species belonging to other modules [@Rodriguez2022].

Regional warming in the West Antarctic Peninsula recorded in the last half-century [@Chown2022] has been one of the main stressors driving changes in Potter Cove (Table 2), a system highly dependent on glacier and sea ice dynamics [@Deregibus2017]. This has caused drastic environmental and biological transformations such as shifts in dominance within the benthic community [@Quartino2013; @Sahade2015; @Schloss2012]. In Potter Cove, there has been a decreasing trend in total sea ice cover since 1991 [@Schloss2012]. Changes in the annual timing of landfast ice formation and the breakup of the sea ice cover has multiple effects on species [@Michel2019]. Warmer winters and springs result in earlier sea ice melt, causing an abrupt increase in the light available for benthic primary producers [@Deregibus2020]. Sea ice also mediates physical disturbances to the benthos by influencing sedimentation and iceberg scouring. These factors affect the production of macroalgae, albeit in opposite ways [@Deregibus2017], and microphytobenthos [@Hoffmann2019]. On the other hand, sea ice is an important habitat for diatoms and their associated consumers, including copepods and the Antarctic krill [@Flores2012], and thus important for bentho-pelagic nutrient and carbon cycling during winter. Additionally, a decrease in winter sea ice cover produces an increase in physical perturbation on benthic shallow communities in coastal shallows due to ice scouring [@Deregibus2017].
The glacier surrounding Potter Cove has been receding at an increasing rate since 1950 [@Ruckamp2011], which has caused a massive discharge of sediment-laden meltwater [@Meredith2018]. Large quantities of suspended particles affect growth, survival, and reproduction of benthic species. This led to a major shift in the benthic community structure, from a filter feeders–ascidian domination to a mixed assemblage with scavengers and opportunistic species [@Sahade2015], and the metabolic balance in benthos went from net autotrophy to heterotrophy [@Braeckman2021]. Additionally, massive stranding events of the tunicate *Salpa thompsoni* and the Antarctic krill linked to the presence of glacial meltwater have been reported [@Fuentes2016].
Rising temperatures leading to ice and glacial melting has also substantial impacts on pelagic primary productivity, since it reduces water salinity, affecting water column stratification, light penetration and nutrient availability for photosynthesis [@Schloss2012]. In Potter Cove, changes in biomass of most phytoplankton species have been observed under heat wave conditions, resulting in a shift from a microplankton to a nanoplankton dominated community [@Antoni2020; @Latorre2023]. This means that in areas strongly affected by glacier melt, the planktonic food web is dominated by the microbial loop (i.e., ciliates and heterotrophic dinoflagellates preys upon nanophytoplankton, which are sequentially available prey for small omnivorous copepods), instead of being predominantly herbivorous [@Garcia2016; @Garcia2019]. In addition, phytoplankton species under these warming conditions showed a decrease in metabolic rate and in the quality of the fatty acid composition [@Latorre2023].

### 2.6 Weddell Sea (Antarctica)

Located between 74 and 78°S, the high Antarctic Weddell Sea shelf spans approximately 450 km from East to West [@Jacob2011] (Figure 1). The water depth ranges from 200 to 500 m, with shallower regions being covered by continental ice that forms the coastline along the eastern and southern parts of the Weddell Sea. The shelf area is characterized by a complex three-dimensional benthic habitat, substantial benthic biomasses, and an intermediate to high diversity [@Teixido2002].

The Weddell Sea food web exhibits a high level of network complexity, featuring the greatest number of nodes (490) and trophic interactions (16041) among the marine food webs of the Southern Hemisphere (Table 1). Its connectance (0.07), mean trophic level (2.62) and omnivory (51%) are intermediate compared to the other food webs (Table 1). Recently, the interaction strengths of this food web were estimated, revealing the presence of numerous weak and few strong interactions [@Marina2024].

In the Weddell Sea, the main stressors are related to warming impacts (sea warming, sea ice extent, iceberg scouring) (Table 2), where sea warming has been substantial since the early 1980s [@Turner2020]. For example, in 2017, the mean temperature for February reached 1.45°C, the highest monthly mean ever recorded, i.e., 0.56°C above the climatological mean [@Turner2020]. Warming has caused spatial and temporal reductions in sea ice, impacting both pelagic and benthic communities [@Constable2014; @Gutt2021]. Since the start of satellite imaging in 1978, sea ice extent has reached new record lows. Some of the most pronounced impacts of decreasing sea ice are negative changes in primary productivity [@Atkinson2004] and declines of the Antarctic krill. Moreover, reduced sea ice cover allows increased access to krill by its predators [@Kawaguchi2009], which further contributes to its decline. Some outcomes of the krill decline are reduced energy intake by higher trophic levels such as humpback whales *Megaptera novaeangliae* [@Pallin2023, @Braithwaite2015] which rely heavily on krill for foraging, as well as reduced carbon export due to fewer fecal pellets [@Pauli2021].
Many higher trophic level species in the Weddell Sea are greatly impacted by sea ice reductions due to loss of habitat and food source availability, such as the Antarctic petrel *Thalassoica antarctica* - one of the most abundant seabirds in the Weddell Sea [@Orgeira2021]. Other impacted sea bird species are the emperor penguin *Aptenodytes forsteri*. Reductions in sea ice constrain its population as evidenced by recent observations in the Bellingshausen Sea region [@Fretwell2023]. The Arctic tern *Sterna paradisaea* spends the summer in the Weddell Sea exploiting krill swarms under receding ice edges. Thus, continued warming is expected to gradually erode the abundance and distribution of marine seabirds in the Weddell Sea [@Orgeira2021]. Many marine mammals depend on for breeding and foraging such as the Weddell and Crabeater seals (*Leptonychotes weddellii* and *Lobodon carcinophagus*) [@Wege2021] and the Humpback whale. Reduced sea ice can significantly affect the breeding success of seals [@Wege2021] and body condition of whales [@Turner2020].
Notothenioid fish, with *Pleuragramma antarcticum* being the most abundant species, confront numerous stressors such as sea warming, sea ice decline, and ocean acidification, posing significant threats to their survival. While certain species exhibit physiological plasticity to cope with increased oxygen demand, most notothenioid fish are stenothermal and incapable of adjusting their metabolic functioning [@Mintenbeck2012]. Projections suggest that the preferred thermal habitat of the Antarctic toothfish, *Dissostichus mawsoni*, an important fish species in the Weddell Sea ecosystem, may contract over the next three decades, underscoring the potential impact of global warming on these species [@Constable2014].
Iceberg scouring is a major factor in driving the high biodiversity of benthic communities in the Weddell Sea [@Gutt2001]. Even at 600 m depths, iceberg scouring has a strong effect on the benthic environment, disrupting the upper layers of the seabed and removing macrofauna. This patchy disturbance and distribution pattern occurs roughly every 200 square meters on the Antarctic continental shelf. Global warming is predicted to increase iceberg scouring frequency [@Gutt2001a; @Smale2008a], disrupting the environment [@Smale2008] with the potential for tipping points  [@Gutt2015].

\newpage
\footnotesize

Table 1. Complexity and structure properties of the marine food webs considered in the present review. Refer to Table S2 for definition of properties. mean TL: mean trophic level. Food webs are ordered by increasing latitude.

--------------------- ----------- ----------- ----------------- ----------------- ------------- -------------- -------------------------------
**Food web**           **Nodes**   **Links**   **Connectance**   **Path length**   **mean TL**   **Omnivory**   **Reference**
--------------------- ----------- ----------- ----------------- ----------------- ------------- -------------- -------------------------------
San Jorge Gulf        165         1015        0.04              2.17              3.02          0.63           @Funes2022

Beagle Channel        145         1115        0.05              2.12              2.37          0.55           @Rodriguez2022

Burdwood Bank         379         1788        0.01              2.99              2.52          0.49           @Marina2024a

Potter Cove           110         649         0.05              2.33              2.22          0.46           @Marina2018; @Rodriguez2022

N Scotia Sea          218         10008       0.21              1.87              3.29          0.73           @Lopez-Lopez2022

S Scotia Sea          192         7241        0.20              1.90              3.21          0.71           @Lopez-Lopez2022

Weddell Sea           490         16041       0.07              2.19              2.62          0.51           @Jacob2011
----------------------------------------------------------------------------------------------------------------------------------------------

\normalsize
## 3. From species’ stressors to food web effects: a qualitative approach

A major challenge in contemporary ecology lies in predicting the effects of stressors on complex multispecies systems, such as food webs. Network analysis has proved to be a powerful tool to tackle this issue, since it can capture the effects of individual and multiple stressors on communities and ecosystems [@Montoya2009; @OGorman2012; @Bruder2019].

Global change stressor effects in the Southwest and the Atlantic sector of the Southern Ocean have been mostly assessed individually and at the organism and/or population, i.e., at the node level (Table 2), with one exception: the effect of fisheries in the San Jorge Gulf food web (see section below for more details). To address the most plausible effects of the main stressors on the selected food webs, given the current information, we formulated a series of alternative hypotheses for each study area. To this aim, we developed a theoretical framework considering the following: a) stressor(s), b) parameter(s) affected, c) node-level properties of the affected species, and d) network-level properties of the food web.

We considered that a stressor will affect one of the following species’ characteristics or parameters: metabolism, population biomass, distribution, and diet (Figure 2). ‘Metabolism’ refers to any change related to metabolic rate, such as reproduction, hatching, larval development, growth and mortality (e.g. growth  effect in filter-feeders due to sediment in water column in Potter Cove; endocrine disruption in fish due to urban pollutants in Beagle Channel). ‘Population biomass’ indicates an effect at the population level, where the density/abundance is being impacted (e.g. abundance decreases in macrobenthos due to iceberg scouring in Weddell Sea). ‘Distribution’ entails a change at the population level in the geographic space occupied by a species, e.g. southward contraction of Antarctic krill due to sea warming of the Scotia Sea. ‘Diet' includes alterations in the prey items of a species at the population level, e.g, due to prey switching, having a direct effect on the structure of the food web, e.g. new prey item (discards) for seabirds due to fishery activities in Burdwood Bank.
Next, we considered node- and network-level properties relevant to the hypothesized stressor effects on the food webs, and which have been previously calculated for the studied food webs (Table 2). At the node-level, we included: a) degree, b) trophic position, c) omnivory index, and d) relative abundance (see Table S1 in Supporting Information for properties of stressed nodes). At the network-level, we considered: a) connectance, b) path length, c) mean trophic level, and d) omnivory (Table 1).




![Conceptual diagram: from species’ stressors to food web effects. A stressor (e.g., global warming) will affect one of the following species’ characteristics: metabolism, population biomass, distribution, and diet. ‘Metabolism’ refers to any change related to metabolic rate, such as reproduction, hatching, larval development, growth and mortality, and contamination due to pollutants. ‘Population biomass’ indicates an effect at the population level, where the density/abundance is being impacted. ‘Distribution’ entails a change at the population level in the geographic space occupied by a species. ‘Diet' includes alterations in the prey items of a species at the population level. Next, we considered node- and network-level properties relevant to the hypothesized stressor effects on the food webs. At the node-level, we included: a) degree, b) trophic position, c) omnivory index, and d) relative abundance. At the network-level, we considered: a) connectance, b) path length, c) mean trophic level, and d) omnivory. Finally, we elaborate a series of competing hypotheses on how the identified stressors might affect food web features (stability, energy flow, topology), combining information on node- and network-level properties.](Figures/Figure2_StressorDiagram.png){width="6.27in"
height="3.528in"}




\newpage
\blandscape
\scriptsize

Table 2. Environmental and anthropogenic stressors reported for the study areas: San Jorge Gulf, Beagle Channel, Burdwood Bank, Scotia Sea (North and South), Potter Cove, and Weddell Sea.
Stressor categories: sea warming; glacial retreat; sediment in the water column; iceberg scouring; sea ice extent; ocean acidification; ocean acidification + plastics; microplastics; mercury; urban & industrial pollution; fishery; alien species.
The species affected were considered at the node level, whereas effects were considered at the organism and population levels.
Categories of affected parameters and variables: metabolism; biomass; distribution; diet (see text for explanation).
“Locality” indicates whether a stressor for a given species was reported for the study area (‘In situ’) or in another area (‘Elsewhere’).

**Study area**                  **Stressor**                                             **Species affected**                                                                                                                                                                                                          **Parameter affected**      **Locality**                                                  **Reference**
------------------------------- -------------------------------------------------------- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- --------------------------- ------------------------------------------------------------- ------------------------------------------------------------------------------
**San Jorge Gulf**                                                                                                                                                                                                                                                                                                                                                                                               
                                Sea warming                                              Fish assemblage & its prey                                                                                                                                                                                                    Distribution                In situ                                                       @Galvan2022
                                Fishery                                                  Demersal fish community                                                                                                                                                                                                       Biomass                     In situ                                                       @Galvan2022
                                Fishery                                                  Macroinvertebrates, fish and seabirds                                                                                                                                                                                       Diet                        In situ                                                       @Gonzalez-Zevallos2006; @Gonzalez-Zevallos2011; @Yorio2017
                                Alien species                                            Fish assemblage & its prey                                                                                                                                                                                                    Distribution                In situ                                                       @Galvan2022; @Ciancio2010
                                Urban & industrial pollution                             Seabirds & benthic assemblage                                                                                                                                                                                                 Biomass                     Elsewhere                                                     @Moore1974; @Buskey2016
**Beagle Channel**                                                                                                                                                                                                                                                                                                                                                                                               
                                Urban & industrial pollution                             Macroalgae; Mytilus edulis chilensis, Patagonotothen tessellata                                                                                                                                                               Metabolism                  In situ                                                       @Giarratano2010; @Ferreira2021; @Kaminsky2024
                                Mercury                                                  Phytoplankton, Zooplankton, *Grimothea gregaria*                                                                                                                                                                              Metabolism                  In situ                                                       @Fioramonti2022
                                Microplastics                                            Mytilus edulis chilensis, Nacella magellanica                                                                                                                                                                                 Metabolism                  In situ                                                       @Perez2020; @Ojeda2021
                                Alien species: Chinook salmon Oncorhynchus tshawytscha   Patagonotothen tessellata, Sprattus fuegensis                                                                                                                                                                                 Diet/Biomass                In situ (the presence), Elsewhere (changes in prey biomass)   @Fernandez2010; @Ciancio2008
**Burdwood Bank**                                                                                                                                                                                                                                                                                                                                                                                                
                                Mercury                                                  Dissostichus eleginoides, Sprattus fuegensis, Patagonotothen ramsayi, Cottoperca trigloides (fish) & squids                                                                                                                 Metabolism                  In situ                                                       @Fioramonti2022
                                Microplastics                                            Henricia obesa & Odontaster penicillatus (sea stars); Patagonotothen guntheri & P. ramsayi (fish)                                                                                                                           Metabolism                  In situ                                                       @Cossi2021; @Perez2021
                                Fishery                                                  Target: Dissostichus eleginoides. Bycatch: Macrourus sp., Coelorinchus sp. (fish), Daption capense, Thalassarche melanophris, Macronectes giganteus, T. chrysostoma, Diomedea epomophora (seabirds), 30+ spp macrobenthos   Biomass                     Elsewhere                                                     @Gaitan2016; @Martinez2022; @APN2022; @Tamini2023
                                Fishery                                                  Thalassarche melanophris, Macronectes giganteus, Daption capense, Diomedea epomophora, M. halli, Procellaria aequinoctialis (seabirds)                                                                                        Diet                        Elsewhere                                                     @Tamini2023
**Scotia Sea, North & South**                                                                                                                                                                                                                                                                                                                                                                                    
                                Mercury                                                  Krefftichthys anderssoni, Protomyctophum bolini, Electrona antarctica, Gymnoscopelus nicholsi, Gymnoscopelus braueri, Dissostichus eleginoides                                                                                Metabolism                  In situ                                                       @Seco2021
                                Ocean acidification + plastics                           Euphausia superba, Limacina retroversa (Pteropoda)                                                                                                                                                                            Metabolism                  In situ                                                       @Rowlands2021; @Manno2022
                                Sea warming                                              Euphausia superba                                                                                                                                                                                                             Metabolism                  In situ                                                       @Murphy2007; @Perry2020
                                Sea warming                                              Euphausia superba                                                                                                                                                                                                             Distribution                In situ                                                       @Atkinson2019
                                Fishery                                                  Euphausia superba                                                                                                                                                                                                             Biomass                     In situ                                                       @Trathan2021
**Potter Cove (Antarctica)**                                                                                                                                                                                                                                                                                                                                                                                     
                                Sediment in water column                                 Microphytobenthos, macroalgae, benthic filter feeders (ascidians), pelagic filter feeders (krill, salps)                                                                                                                      Metabolism                  In situ                                                       @Sahade2015; @Deregibus2016; @Fuentes2016; @Hoffmann2019
                                Sea ice extent                                           Krill                                                                                                                                                                                                                         Biomass                     Elsewhere                                                     @Flores2012
                                Sea ice extent                                           Benthic community (macroalgae, invertebrates)                                                                                                                                                                                 Metabolism                  Elsewhere                                                     @Clark2013; @Campana2018
                                Glacial retreat                                          Benthic community (macroalgae, invertebrates)                                                                                                                                                                                 Biomass                     In situ                                                       @Quartino2013; @Lagger2017; @Lagger2018
                                Iceberg scouring                                         Benthic community                                                                                                                                                                                                             Biomass                     In situ                                                       @Deregibus2017; @Deregibus2023
                                Sea warming                                              Phytoplankton                                                                                                                                                                                                                 Metabolism, biomass         In situ                                                       @Antoni2020; @Latorre2023
                                Sea warming                                              Zooplankton                                                                                                                                                                                                                   Metabolism, biomass, diet   In situ                                                       @Garcia2016; @Garcia2019
                                Sea warming                                              Fish                                                                                                                                                                                                                          Metabolism                  In situ, elsewhere                                            @Strobel2013; @Souza2018; @Saravia2021
**Weddell Sea (Antarctica)**                                                                                                                                                                                                                                                                                                                                                                                     
                                Iceberg scouring                                         Macrobentos                                                                                                                                                                                                                   Biomass                     In situ                                                       @Isla2023; @Gutt2015; @Smale2008a; @Gutt1996
                                Iceberg scouring                                         Hexactinellida sponges                                                                                                                                                                                                        Biomass                     In situ                                                       @Gutt2001; @Pineda-Metz2020; @Gutt2001a; @Gutt2003
                                Ocean acidification                                      Primary producers / krill / foraminifera / flagellates                                                                                                                                                                        Metabolism                  Elsewhere                                                     @Deppeler2020; @Isla2023; @Gutt2015; @Moy2009
                                Ocean acidification                                      Euphausia superba, Pleuragramma antarcticum                                                                                                                                                                                   Metabolism                  In situ                                                       @Kawaguchi2010; @Kawaguchi2013; @Pinones2016; @Mintenbeck2012
                                Sea warming                                              Large (diatoms) & small (cryptophytes) phytoplankton, zooplankton (salps)                                                                                                                                                     Metabolism                  Elsewhere                                                     @Isla2023; @Gutt2015; @Trebilco2020
                                Sea warming                                              Euphausia superba, Nototheniid fish, Pleuragramma antarcticum                                                                                                                                                               Metabolism                  In situ                                                       @Meyer2017; @Hill2013; @Mintenbeck2012; @Constable2014; @Mintenbeck2012
                                Sea ice extent                                           Phytoplankton, Lobodon carcinophaga, Hydrurga leptonyx, Leptonychotes weddellii, Ommataphoca rossii, Mirounga leonina, Arctocephalus gazella                                                                                  Metabolism                  In situ                                                       @Pineda-Metz2020; @Wege2021; @Siniff2008
                                Sea ice extent                                           Euphausia superba, Pleuragramma antarcticum, Pagodroma nivea, Thalassoica antarctica, Pygoscelis adeliae                                                                                                                      Metabolism                  In situ                                                       @Orgeira2021; @Braithwaite2015; @Hill2013; @Mintenbeck2012
                                Sea ice extent                                           Megaptera novaeangliae                                                                                                                                                                                                        Metabolism                  Elsewhere                                                     @Pallin2023
                                Sea ice extent                                           Aptenodytes forsteri                                                                                                                                                                                                          Metabolism                  Elsewhere                                                     @Orgeira2021




\elandscape

\normalsize




### 3.1 Hypotheses on the main stressor effects in food webs in a southwest Atlantic - Antarctic gradient

The most common stressor reported along the Southwest Atlantic - Antarctic gradient is global warming, except for Beagle Channel and Burdwood Bank, which are more influenced by the introduction of an alien species and fisheries, respectively (Section 2, Table 2). The main characteristics of global warming in the region, and the most plausible drivers of change, are sea warming, glacial retreat, elevated sediment input to the water column, and reduction of the sea ice extent. These drivers act in different ways and magnitudes in the studied locations along the latitudinal gradient. 
Despite emphasizing global warming in this section, this does not mean that no other stressors act or interact with global warming in the study systems, potentially buffering or even amplifying the overall effect on the food web (e.g. sea warming and fishery in San Jorge Gulf).
Climate change has led to several well-documented impacts on marine species regarding distributional shifts induced by warming of marine currents [@Poloczanska2013; @Wu2012; @Verges2019]. Furthermore, warmer temperatures increase species metabolic rates [@Brown2004]. Changes in metabolic rates can subsequently translate into shifts in species traits (e.g. body size, @Vucic-Pestic2011; @Klein2018), population biomass [@Perry2020], and distribution [@Kortsch2015]. Alterations in the species body size and distributions have ripple effects on feeding interactions, for example, it can introduce new feeding interactions [@Pecuchet2020; @Verges2014], modify existing ones, and shorten energy pathways [@Bartley2019; @OGorman2019], and reduce trophic efficiencies [@Vucic-Pestic2011].

#### 3.1.1 San Jorge Gulf

In recent years, several new fish [@Galvan2022] and macroinvertebrates species [@Vinuesa2005; @Lopez-Gappa2022] were registered in Patagonia, mostly in San Jorge Gulf concerning the southward range shift of warm-temperate species. This distributional change is driven by the tropicalization of temperate waters caused by sea warming [@Verges2014; @Verges2019]. Because of its location in the ecotone between two biogeographic provinces, the Argentine (30°S - 44°S) and the Magellanic (43°S - 55°S) [@Balech2008], the San Jorge Gulf is prone to changes in species composition. We hypothesize that sea warming will alter the food web structure topologically, by increasing the number of species and interactions. Newcomers are, in general, mid-trophic level species with generalist diets, hence an increase in food web connectance may be expected [@Bartley2019]. In another temperate ecosystem, an increase in the number of fish species led to increases in functional diversity and predation rate [@Sgarlatta2023]; consequences that may also be expected in San Jorge Gulf. Given the short path length of the San Jorge Gulf food web, the disturbances from the listed stressors are expected to spread to many species of the food web (Table 3). However, it has to be acknowledged that the increase in functional diversity driven by the range expansion of warm-temperate species is contrary to the process of homogenization and loss of functional diversity in the area driven by trawl fisheries [@Rincon-Diaz2021].

#### 3.1.2 Scotia Sea

In the middle of the latitudinal gradient considered in this study, the Scotia Sea has experienced one of the largest levels of sea warming of any polar region [@Whitehouse2008; @Atkinson2019]. @Lopez-Lopez2022 suggested that the southward distributional shift of generalist predators from the northern towards southern Scotia Sea increases network connectance of the latter, while decreasing its modularity. The lower modularity may increase the probability of perturbations spreading through the network [@Stouffer2011]. In the northern Scotia Sea around South Georgia Island, we suggest that the declining krill biomass driven by sea warming [@Atkinson2019], ocean acidification and pollution synergy [@Rowlands2021], will reduce the energy transfer to top predators like seabirds and marine mammals. However, this may be buffered because the dominant copepod species have maintained their distribution [@Tarling2018], but most importantly shown an abundance increase in recent decades likely due to reduced predation and competition for food [@Ward2018]. The potential compensation for the decrease in krill by increasing abundance of copepod may buffer against structural and functional changes in the food web (Table 3), since krill and copepod play similar (central) roles in the food web, characterized by a high degree and mid-trophic position.

#### 3.1.3 Potter Cove (Antarctica)

In Potter Cove, a fjord-like Antarctic ecosystem, the repercussions of climate change extend across numerous species. Noteworthy, these effects are non-uniform within the food web, manifesting differently across its pelagic and benthic compartments.
Potter Cove has recently experienced frequent events of marine heatwaves, i.e., prolonged periods of anomalously high sea surface temperature [@Oliver2018; @Latorre2023]. This has led to decreases in biomasses of different planktonic functional groups [@Garcia2019; @Latorre2023]. Given the relatively low abundance of phytoplankton and zooplankton low mean degree (Table S1), resulting in weak interaction strengths between these low trophic levels and higher ones [@Rodriguez2024], added to the modular configuration of the food web [@Rodriguez2022], we hypothesize that changes in these nodes due to warming will be retained at the lower trophic levels of the pelagic compartment and will not expand to higher trophic levels.
Macroalgae, important benthic primary producers, are being influenced by the decrease in winter sea ice cover (higher light availability), the increased levels of sediments in the water column due to glacial melt run-off (lower light penetration) and the newly free-ice areas available for colonization associated to glacier retreat. The local effect of climate change on macroalgae is a net increase in their production and macroalgal detritus [@Deregibus2023; @Iken2023; @Braeckman2019]. On the other hand, increased glacial runoff lead to a decrease in net primary production of benthic microalgae [@Hoffmann2019]; reduced secondary benthic production; changes on the benthic community composition and an expansion of its distribution towards newly free-ice areas, specially filter and deposit feeders species [@Braeckman2024; @Sahade2015; @Pasotti2015]. In an increasing glacial melt disturbance scenario, it’s expected a shift in the food sources of benthic species towards grazing on macroalgal and their detritus [@Braeckman2024]. 
It has been proposed that larger diversity in primary sources can support a more diverse food web with more specialized consumers [@Iken2023]. Given the high relative abundance and the high degree of the macroalgae functional group (Table S1), we expect a longer benthic food web (i.e., number of interactions connecting low and high-trophic levels), wider consumer trophic niches, meaning an increase in omnivory, and a more stable benthic food web as sea ice cover decreases and glaciers retreat due to global warming.
As a net effect of climate change on the overall Potter Cove food web, we expect a significant shift in energy fluxes, rather than drastic alterations in the topological structure, affecting the transfer of energy from lower to higher trophic levels.

#### 3.1.4 Weddell Sea (Antarctica)

In the southernmost food web, the Weddell Sea, the main effect of global warming is the decrease in sea ice extent, with reported anomalies in the past summer seasons [@Fretwell2023]. Declining sea ice extent has reduced the abundance of krill [@Atkinson2004; @Flores2012], and produced an increase in phytoplankton productivity [@Isla2023; @Pinkerton2021], altering the plankton community structure, and benefiting cryptophytes over diatoms [@Lin2021]. Moreover, habitat loss from sea ice decline will reduce the foraging success and breeding sites of seabirds (e.g., snow petrel *P. nivea* and emperor penguin), decreasing their population biomassess and modifying their distributions.
The projected rise in iceberg scouring is expected to significantly alter the biomass and community structure of macrobenthos, which in turn will impact mid-trophic level predators such as demersal fish [@Gutt2001a; @Mintenbeck2012]. While we do not anticipate large-scale topological changes affecting mean food web attributes, local extinctions may produce changes in the interactions, especially impacting benthic species [@Gutt2003]. Given that the impacted species—whether individually like krill, or collectively like macrobenthos and notothenioids (e.g., *P. antarcticum*)—present a mid-trophic position, high population biomasses and high degree (Table S1), we hypothesize that significant shifts in energy fluxes will occur (Table 3). Additionally, the food web's low proportion of omnivores suggests reduced system resilience (Table 1), increasing the likelihood of regime changes [@Gutt2015].

#### 3.1.5 Beagle Channel and Burdwood Bank

The Beagle Channel and Burdwood Bank -the two ecosystems in the subantarctic region- are more affected by other stressors than warming. That said, there are impacts of warming in these ecosystems, especially  affecting vertebrate and invertebrate species [@Franco2020], but generally studies addressing these impacts are lacking for the Beagle Channel and Burdwood Bank ecosystems.
In the Beagle Channel, the introduction of chinook salmon, a non-native species, poses a significant risk to the existing food web [@Fernandez2010]. We hypothesize that chinook salmon's predation on Fuegian sprat and black southern cod will disrupt the established patterns of interaction within the food web. Both of these prey species are crucial for food web dynamics due to their mid-trophic positions and relatively high abundance (Table S1). Moreover, we expect that changes in the black southern cod population will have a more significant impact on the food web than changes in the Fuegian sprat population, as the black southern cod has a higher degree (Table S1). Overall, these disruptions could have far-reaching effects on the ecosystem. This is particularly concerning given the short path length of the food web, which means that changes can quickly propagate through the system, affecting many species and potentially destabilizing the entire network. This phenomenon is further heightened by the ecosystem's inherent vulnerability to changes at mid-trophic levels, often referred to as wasp-waist control (Table 3).
In the Burdwood Bank region, fishing activities may be the main stressor causing shifts in the food web (Table 2). We hypothesize that a combination of factors will destabilize the already fragile ecosystem, characterized by low connectance and low omnivory (Table 1). These factors include a decline in the biomass of the Patagonian toothfish -a highly-connected, key species (Table S1)- as well as smaller changes in the population biomass of four mid trophic level fish species, five top trophic level seabird species, and over 30 types of benthic macroinvertebrates due to bycatch [@Gaitan2016; @Martinez2022; @Tamini2023]. Additionally, alterations in the diets of six seabird species, caused by discarded catch [@Tamini2023], are expected to disrupt the energy flow and further reduce the stability of the food web (Table 3).

\scriptsize

Table 3. Summary of hypothesized food web (FW) effects according to the main stressors
reported for each study area. \*Industrial trawl fishery ceased in 2015 remaining artisanal trawling
activity.

+-----------------------+----------------------+-----------------------+
| **Study area**        | **Stressor**         | **Hypothesis on food  |
|                       |                      |       web effects**   |
+=======================+======================+=======================+
| **San Jorge Gulf**    |                      |                       |
+-----------------------+----------------------+-----------------------+
|                       | Fishery\*            | ↑ FW connectance      |
|                       |                      |                       |
|                       |                      | ↓ FW stability        |
|                       |                      |                       |
|                       |                      | ↓ functional          |
|                       |                      | diversity             |
+-----------------------+----------------------+-----------------------+
|                       | Sea warming          | Shifts in FW topology |
|                       |                      |                       |
|                       |                      | ↑ FW connectance      |
|                       |                      |                       |
|                       |                      | ↑ functional          |
|                       |                      | diversity             |
+-----------------------+----------------------+-----------------------+
| **Beagle Channel**    |                      |                       |
+-----------------------+----------------------+-----------------------+
|                       | Alien species        | Shifts in FW topology |
|                       |                      |                       |
|                       |                      | ↑ spread of           |
|                       |                      | perturbations         |
+-----------------------+----------------------+-----------------------+
| **Burdwood Bank**     |                      |                       |
+-----------------------+----------------------+-----------------------+
|                       | Fishery              | Shifts in main energy |
|                       |                      | fluxes                |
|                       |                      |                       |
|                       |                      | ↓ FW stability        |
+-----------------------+----------------------+-----------------------+
| **Scotia Sea**        |                      |                       |
+-----------------------+----------------------+-----------------------+
|                       | Sea warming          | ↑ FW connectance      |
|                       |                      |                       |
|                       |                      | ↓ FW modularity       |
|                       |                      |                       |
|                       |                      | ↓ energy transfer to  |
|                       |                      | high TLs              |
|                       |                      |                       |
|                       |                      | ↑ spread of           |
|                       |                      | perturbation          |
+-----------------------+----------------------+-----------------------+
| **Potter Cove         |                      |                       |
| (Antarctica)**        |                      |                       |
+-----------------------+----------------------+-----------------------+
|                       | Sea warming          | ↓ perturbation        |
|                       |                      | spreading             |
+-----------------------+----------------------+-----------------------+
|                       | Sea ice decline +    | ↑ FW chain length & |
|                       | glacial retreat      | ↑ trophic niches    |
+-----------------------+----------------------+-----------------------+
| **Weddell Sea         |                      |                       |
| (Antarctica)**        |                      |                       |
+-----------------------+----------------------+-----------------------+
|                       | Sea ice decline +    | Shifts in main energy |
|                       | iceberg scouring     | fluxes                |
|                       |                      |                       |
|                       |                      | ↑ likelihood of       |
|                       |                      | regime shifts         |
|                       |                      |                       |
|                       |                      | ↓ resilience          |
+-----------------------+----------------------+-----------------------+

\normalsize

## 4. Gaps and future perspectives

In the selected study areas along the Southwest Atlantic to Antarctic latitudinal axis, several stressors may directly affect consumers’ diets triggered by modified environmental conditions (sea warming, reduced sea ice extent) and new species (due to species’ distributional shifts and introductions). Moreover, the population trends (biomasses and abundances) of important species are also changing [@Funes2020; @Hindell2020; @Woods2023] driving shifts in their roles as either predators or prey (e.g. @Belleggia2017, @Pasti2021). These diet and population biomass shifts should be investigated to generate reliable predictions of food web responses to multiple stressors in the Southwest Atlantic - Antarctic region. One could argue that both shifts might increase the complexity of food webs in the short term by adding generalist predators or new prey (e.g., @Cordone2023) or by enabling discard consumption (e.g. @Funes2022). However, in the long term, both stressors may lead to the biological extinction of certain prey and competitors (e.g. @Anton2019) or a significant reduction in target and incidental catch species (e.g. @Dulvy2014), thereby promoting food web simplification and decreases in robustness.

Since this review deals with qualitative data of predator-prey interactions and stressor effects influencing them, adding quantitative data to the food webs (e.g., interaction strength) and to the stressors (e.g., magnitude) would lead to a better understanding of how a given stressor acts on specific species which might translate into food web effects.
In this context, it would be useful to develop quantitative food web models where the strength of interactions reflects energy fluxes among species [@Kortsch2021; @Nilsson2016]. Emerging methods such as bioenergetic food web modeling have been proposed in this regard and present promising ways to estimate shifts in species interactions and energy fluxes within food webs as a response to stressors [@Gauzens2023;  @Gellner2023]. Shifts that can lead to changes in overall ecosystem functioning and stability.

Regarding knowledge and data gaps on species and their stressors, especially the Beagle Channel and Burdwood Bank are poorly sampled study regions. Almost no information exists on the impact of global warming (sea warming, glacial retreat, ocean acidification) on communities in these ecosystems, although warming of mid-water and bottom layers has been shown at a regional scale [@Franco2020]. Yet, in Beagle Channel recent experimental studies have tested the tolerance of fish to scenarios of sea warming and/or acidification suggesting high vulnerability to projected climate-driven environmental conditions [@Lattuca2018; @Lattuca2023].

Analyzing the impact of multiple stressors through observational studies is challenging [@Gutt2021]. This complexity arises partly because of the potential for antagonistic effects, where impacts cancel each other out, or synergistic effects, where the combined impact is greater than the sum of individual effects [@Boyd2015; @Cote2016]. Moreover, these interactive effects are complicated to handle in the framework of complex food webs. The number of pathways through which a species may affect or be affected by other species, and through which stressors may permeate communities, increases exponentially with the number of species and interactions in a network [@Menge1995]. To tackle this complexity, @Beauchesne2021 developed a theory-grounded approach using motifs (i.e. groups of species that, when put together, construct whole food webs) to simplify food webs; a methodology that could be applied to our food web study cases.

In this review, we proposed a series of alternative hypotheses on how global stressors may affect food webs in the Southwest Atlantic to Southern Ocean. Despite being qualitative, this is a first important step in synthesizing food webs and stressor effects on species and food webs for this region. These qualitative assessments must be complemented with further investigations that test their validity. To achieve this, we suggest using a combination of observational data such as reported biomass changes and historic records of sea temperature for the region [e.g., @Laptikhovsky2013; @Funes2019; @Franco2020a; @Winter2023], and food web modeling methods such as stressor-response matrices (@Bracewell2019) and flux modeling (e.g., @Gauzens2019; @Beauchesne2021; @Polazzo2022).

## 5. Conclusions

We reviewed global change stressors acting in six different areas along a large-scale latitudinal gradient from temperate Atlantic to cold Antarctic ecosystems. Using a theoretical framework that combines species and food web-level data, we suggest how warming effects may impact food web structure and functioning. Apart from an important amount of uncertainty, these qualitative predictions are intended to serve as the basis for future studies in marine ecosystems of the Southern Hemisphere that aim at quantifying the magnitude of these stressors and how they are affecting quantitative food web properties, such as energy fluxes and stability. There is an urgent need to assess these changes using a holistic and quantitative framework where the magnitude of stressors and species interactions are taken into account.

## Acknowledgements

This review is a product of the project “¿Cuáles son los efectos de los cambios ambientales antropogénicos en las interacciones tróficas de las comunidades de los ecosistemas marinos en el gradiente latitudinal Atlántico Sudoccidental - Antártida?”, funded by Consejo Nacional de Investigaciones Científicas (CONICET, code PIP 2022-2024 #0907), Argentina. S.K. gratefully acknowledges the support from the Walter and Andrée de Nottbeck Foundation, Finland.


## Competing interests

The authors declare there are no competing interests.

## Data Availability

All data used in this manuscript is publicly available and compiled on a 
Github repository https://github.com/EcoComplex/SouthFWReview and Zenodo 
https://zenodo.org/doi/10.5281/zenodo.11060734

## References
