---
title: "Collapse Weddell and Check consistency"
author: "L.A.S."
output: html_document
editor_options: 
  chunk_output_type: console
---

## Setup

```{r setup, eval=T,echo=FALSE }
#load(".RData")
require(igraph)
require(stringr)
require(devtools)
if( require(meweasmo) == FALSE)
  install_github("lsaravia/meweasmo")
if( require(multiweb) == FALSE)
  install_github("lsaravia/multiweb")
require(tidyverse)


```

# Check Weddell Sea

```{r WeddellSea, eval=F,echo=F,message=T,warning=T}
 
#
dtot <- read_csv("Data/WeddellSea_links_original.csv")

# Check valid names 
#
# Predators
require(taxize)
dfn <- unique(dtot$consumer)
con_names <- gnr_resolve(dfn, best_match_only = TRUE, canonical=TRUE)
# Species not found
anti_join(data.frame(user_supplied_name=dfn),con_names)
# 1 Cadulus dalli antarcticum

# CLasificación completa
clasall <- classification(dfn, db = 'itis') #


# Preys
#
dfn <- unique(dtot$resource)
res_names <- gnr_resolve(dfn, best_match_only = TRUE, canonical=TRUE)
anti_join(data.frame(user_supplied_name=dfn),res_names)
# 1             Phytodetritus
# 2                  Sediment
# 3         Silicioflagellata
# 4 Cadulus dalli antarcticum

gM <- graph_from_edgelist(as.matrix(dtot), directed  = T)

# Basal species
#
basal_sp <- (V(gM)[ (degree(gM,mode="in")==0) ])$name
basal_sp



# CLasificación completa
# clasall <- classification(basal_sp, db = 'itis') # 24 not found

# Solamente clase
class <- tax_name(basal_sp, get = "class", db = "itis")
class %>% count(is.na(class))                                # 27 NA
class <- class%>% mutate(genera= stringr::word(query)) %>% rename( species = query ) %>% select(genera,species,class)

unique(class$genera)

#write_tsv(class,"Data/WeddellSea_basal.dat")
class<-read_tsv("Data/WeddellSea_basal.dat")

# Genera tabla genero clase para reemplazar el nombre de la especie por la clase solo en el caso de Bacillariophyceae

#remove "Phytodetritus" and "Sediment"
row_names_to_remove<-c("Phytodetritus","Sediment")
class<-class[!(class$genera %in% row_names_to_remove),]

class  <- class %>% 
mutate(class = case_when(class %in% c("Prymnesiophyceae", "Chrysophyceae") ~ "Phytoplankton_other",TRUE ~ class))

class  <- class %>% 
mutate(class = case_when(species %in% c("Silicioflagellata") ~ "Phytoplankton_other",TRUE ~ class))

#add a resource link to Alcyonium antarcticum
dtot<-rbind(dtot, c("Phytodetritus", "Alcyonium antarcticum"))

#
gencla <- class %>% filter(!is.na(class)) %>%  distinct(genera,class) %>%  filter(class=="Bacillariophyceae")
#
gencla <- add_case(gencla, genera="Nitzschia", class="Bacillariophyceae" )
dim(gencla)

gencla_other <- class %>% filter(!is.na(class)) %>%  distinct(genera,class) %>%  filter(class=="Phytoplankton_other")

sapply( 1:nrow(dtot), function(i) {
  res_gen <- stringr::word(dtot$resource[i]) 
  rep_cla <- gencla %>% filter(genera == res_gen) 
  if(nrow(rep_cla)==1)
    dtot$resource[i] <<- rep_cla$class
  
  rep_cla_other <- gencla_other %>% filter(genera == res_gen) 
  if(nrow(rep_cla_other)==1)
    dtot$resource[i] <<- rep_cla_other$class
})

#
collapsed_w <- dtot %>% distinct()
gM <- graph_from_edgelist(as.matrix(collapsed_w), directed  = T)

# Basal species
#
new_basal_sp <- (V(gM)[ (degree(gM,mode="in")==0) ])$name
new_basal_sp

#I FIXED THESE ISSUES!!! (Susanne)

#        Dictyocha     Chrysophyceae --> phytoplankton == silicioflagellata 
#      Phaeocystis  Prymnesiophyceae --> phytoplankton
#      
#   Alcyonium antarcticum  --> Coral not basal
#   Silicioflagellata     --> ??? Chrysophyceae? 
# 

calc_topological_indices(gM)
write_csv(collapsed_w,"Data/Weddell_collapsed_links.csv")

collapsed_w <- read_csv("Data/Weddell_collapsed_links.csv")


```


# Weddell Sea get full classification 


```{r, WeddellSeaFullClass, eval=F,echo=F,message=T,warning=T}
require(tidyverse)
require(igraph)
#
# Auxiliary functions
#
source("R/functions.R")

#
# Food-web data 
#
dtot <- read_csv("Data/WeddellSea_links_original.csv")

if( file.exists("Data/WeddellSea_clasification.rds")) {
  
  classall_df <- readRDS("Data/WeddellSea_clasification.rds")
  
} else {
    
  # Read complete clasification from Taxonomic databases
  #
  require(taxize)
  dfn <- unique(dtot$consumer)
  dfn <- c(dfn, unique(dtot$resource))
  dfn <- unique(dfn)
  
  # CLasificación completa
  
  clasall <- classification(dfn, db = 'gbif') #
  
  class_list <- class_to_df(clasall)
  
  classall_df <- class_list[[1]]
  
  #
  # Search in worms records Not found in gbif
  #
  
  dfn <- class_list[[2]]$Taxon
  
  
  clasall <- classification(dfn, db = 'worms') #
  
  class_list <- class_to_df(clasall)
  
  tmp_df <- class_list[[1]]
  names(tmp_df) <- tolower(names(tmp_df))
  names(tmp_df)[1] <- "Taxon"
  dfn <- class_list[[2]]$Taxon
  names(classall_df)
  classall_df <- bind_rows(classall_df,tmp_df)
  saveRDS(classall_df,file="Data/WeddellSea_clasification.rds")
}


# Search in any field of the df
#
search_value <- "foram"
result <- classall_df %>% filter(if_any(kingdom:suborder, ~grepl(search_value, .,ignore.case=TRUE)))


# Replace the species nodes contained in `result` to the value of the field result$class 
# to obtain the degree of the collapsed node
#
search_value <- "Hexactinellida"
result <- classall_df %>% filter(if_any(kingdom:suborder, ~grepl(search_value, .,ignore.case=TRUE)))
dtot1 <- replace_nodes(dtot, result, "class")
collapsed_w <- dtot1 %>% distinct()
gM <- graph_from_edgelist(as.matrix(collapsed_w), directed  = T)

degree(gM)[search_value]


# Replace the species nodes contained in `result` to the value of the field result$class 
# to obtain the degree of the collapsed node
#
search_value <- "Bacillariophyceae"
result <- classall_df %>% filter(if_any(kingdom:suborder, ~grepl(search_value, .,ignore.case=TRUE)))

dtot1 <- replace_nodes(dtot, result, "class")
collapsed_w <- dtot1 %>% distinct()
gM <- graph_from_edgelist(as.matrix(collapsed_w), directed  = T)

degree(gM)["Bacillariophyceae"]
degree(gM)["Pleuragramma antarcticum"]
require(NetIndices)
a <- get.adjacency(gM,sparse=F)
tl <- TrophInd(a)
tl[rownames(tl)=="Pleuragramma antarcticum",]
tl[rownames(tl)=="Pygoscelis adeliae",]
trophiclevels(gM)


search_value <- "Chromista"
result <- classall_df %>% filter(if_any(kingdom:suborder, ~grepl(search_value, .,ignore.case=TRUE)))


search_value <- "Dictyocha"
result <- classall_df %>% filter(if_any(kingdom:suborder, ~grepl(search_value, .,ignore.case=TRUE)))
```

